#!/bin/bash
set -e
cd "$(dirname "$0")/.."

if ! [ -x "$(command -v node)" ]; then
   echo 'node is not installed, please install. Exiting.'
   exit 1
fi

script/update
bundle exec bin/rails server
./
